FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app
COPY reporter/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY reporter/main.py ./main.py

CMD ["python", "-u", "/app/main.py"]
